### ISSUE TITLE
adhoc play queue

### ISSUE THREAD

**Issue by ramSeraph** [orizens/echoes#41]
It would be lovely to have an adhoc play queue. That is, when you are playing a song, you might want to search for another song and queue it up to play next. I am not sure its already available. I have only seen Echoes today and spent around 30 mins with it. So, if it already exists, can you tell me how i can do that. Thanks.

**Comment by orizens** [comment]
hi @ramSeraph.

The feature has been added to the upcoming future version of Echoes.
Currently, it is available in the angular branch of echoes.

**Comment by orizens** [comment]
hi @ramSeraph 
queue is now available in the new version of echoes.

thanks.
