### ISSUE TITLE
Error on application init

### ISSUE THREAD

**Issue by nbiton** [orizens/echoes#56]
This error is thrown:

`
TypeError: Cannot read property 'childNodes' of undefined
`

This prevents the application from being initialized properly.

**Comment by orizens** [comment]
hi @nbiton   
i can't reproduce it. maybe an extension you use?
one more thing - are you using chrome?

**Comment by nbiton** [comment]
Yes, it appears that one of my chrome extensions is causing the problem, thanks.

**Comment by orizens** [comment]
thanks.
care to share which extension is that?

**Comment by nbiton** [comment]
Yeah, it's a simple chrome extension I worked on a while ago, called [Glove](https://chrome.google.com/webstore/detail/glove/abdgoalibdacpnmknnpkgnfllphboefb?utm_source=chrome-ntp-icon).

It's the first time I've seen interfering with any website. It was running along side echoes many times :)
