### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by dnbard** [orizens/echoes#64]
I've got this after the scrolling: 

![2015-08-23_1600](https://cloud.githubusercontent.com/assets/4028472/9428277/2af13c4e-49b0-11e5-98f6-3ba80e74a406.png)

Browser: Chrome 44
OS: Windows 7

**Comment by orizens** [comment]
hi @dnbard 
Unfortunately, i get this too in **Windows** (version 8.1) only.
I suspect it has something to do with Chrome and css's "translate3d", but am not sure.

**Comment by orizens** [comment]
I found a similar [bug description in chrome](https://code.google.com/p/chromium/issues/detail?id=143354)
I will try to implement the suggested patch.

**Comment by orizens** [comment]
i have a new direction regarding this issue:
a possible source for this problem is the css "transform" rule for the dropdowns/dropups of the media info and the user menu.

**Comment by dnbard** [comment]
Looks great! :+1:

**Comment by orizens** [comment]
@dnbard 
thanks for checking
