### ISSUE TITLE
Curiosity about debugInfoEnabled

### ISSUE THREAD

**Issue by calamarico** [orizens/echoes#86]
Hi! Orizens, i like your app!

This issue is only to say that there is an issue using debugInfoEnabled(true) (in echoes/src/app/app.production.config.js)

If the client browser has a extension like angular-performance or batarang (i have no tested batarang but i think is the same), the extension, because it's using getRootScope, throws an exception and call to angular.reloadDebugInfo() !!!
Your app suffers a reload...
I have solved in my app overwritting that function:

function config ($compileProvider) {
  angular.reloadDebugInfo = angular.noop;
  $compileProvider.debugInfoEnabled(false);
}

Respects

**Comment by orizens** [comment]
hi @calamarico 
thanks for complements.
the **app.production.config.js** is compiled for production only - not in development mode.
