### ISSUE TITLE
SignIn from body button isn't working

### ISSUE THREAD

**Issue by tulitheprogrammer** [orizens/echoes#96]
when you use the SPA 
1. login using GOOGLE++
2.  top right dropdown SIGN OUT
3. try  to log in through middle page button doesn't work
4. sign in available only through dropdown

**Comment by orizens** [comment]
thanks - this problem has popped up recently.
will check.

**Comment by orizens** [comment]
@tulitheprogrammer have you authorized Echoes to your google+ user? does your google+ user integrated with your youtube profile?
