### ISSUE TITLE
General Tought: The Effect lib need to be inside the Store

### ISSUE THREAD

**Issue by ChenReuven** [orizens/echoes#97]
the effect is direct related to Store, so i think it better that all his functionality need to be inside the "Store" directory.

What do u think? (Btw i understand also that is part of the core but still i think that proper location need to be inside the "store directory") :)

**Comment by orizens** [comment]
hi @ChenReuven 
this discussion belongs to http://github.com/orizens/echoes-ng2

**Comment by ChenReuven** [comment]
oops :), closed
